export default defineStore("user.lecture", {
  state() {
    return {
      page: 1,
      pageSize: 10,
      totalCount: 63,
      // state: available(사용가능), expired(만료), redeemed(사용완료)
      items: {
        0: {
          state: "수강중",
          category: "비교과 과정",
          institution: "아이스크림홈런",
          title: "초등 _ 4학년_영어 강의명(강좌명) 노출영역 노출영역",
          date: "2023.02.15 ~ 2023.02.30",
          progress: 40,
        },
        1: {
          state: "완료",
          category: "온라인",
          institution: "해커스",
          title: "해커스 초등과정",
          date: "2023.04.15 ~ 2023.05.30",
          progress: 35,
        },
        2: {
          state: "수강중",
          category: "비교과 과정",
          institution: "아이스크림홈런",
          title: "초등 _ 4학년_영어 강의명(강좌명) 노출영역 노출영역",
          date: "2023.02.15 ~ 2023.02.30",
          progress: 20,
        },
        3: {
          state: "수강중",
          category: "비교과 과정",
          institution: "아이스크림홈런",
          title: "초등 _ 4학년_영어 강의명(강좌명) 노출영역 노출영역",
          date: "2023.02.15 ~ 2023.02.30",
          progress: 90,
        },
        4: {
          state: "수강중",
          category: "비교과 과정",
          institution: "아이스크림홈런",
          title: "초등 _ 4학년_영어 강의명(강좌명) 노출영역 노출영역",
          date: "2023.02.15 ~ 2023.02.30",
          progress: 10,
        },
        5: {
          state: "수강중",
          category: "비교과 과정",
          institution: "아이스크림홈런",
          title: "초등 _ 4학년_영어 강의명(강좌명) 노출영역 노출영역",
          date: "2023.02.15 ~ 2023.02.30",
          progress: 0,
        },
        6: {
          state: "수강중",
          category: "비교과 과정",
          institution: "아이스크림홈런",
          title: "초등 _ 4학년_영어 강의명(강좌명) 노출영역 노출영역",
          date: "2023.02.15 ~ 2023.02.30",
          progress: 100,
        },
        7: {
          state: "수강중",
          category: "비교과 과정",
          institution: "아이스크림홈런",
          title: "초등 _ 4학년_영어 강의명(강좌명) 노출영역 노출영역",
          date: "2023.02.15 ~ 2023.02.30",
          progress: 50,
        },
        8: {
          state: "수강중",
          category: "비교과 과정",
          institution: "아이스크림홈런",
          title: "초등 _ 4학년_영어 강의명(강좌명) 노출영역 노출영역",
          date: "2023.02.15 ~ 2023.02.30",
          progress: 50,
        },
        9: {
          state: "수강중",
          category: "비교과 과정",
          institution: "아이스크림홈런",
          title: "초등 _ 4학년_영어 강의명(강좌명) 노출영역 노출영역",
          date: "2023.02.15 ~ 2023.02.30",
          progress: 11,
        },
      },
      keys: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    };
  },
});
