export default defineStore("user.lectureSuggestion", {
  state() {
    return {
      page: 1,
      pageSize: 10,
      totalCount: 63,
      items: {
        0: {
          state: "접수 완료",
          type: "유튜브",
          category: "인문",
          subCategory: "언어/문학",
          title: "비밀번호를 분실했습니다. 빨리 찾고싶어요 알려주세요!",
          date: "2023.02.15",
        },
        1: {
          state: "검토중",
          type: "오프라인",
          category: "인문",
          subCategory: "언어/문학",
          title: "비밀번호를 분실했습니다. 빨리 찾고싶어요 알려주세요!",
          date: "2023.02.15",
        },
        2: {
          state: "반려",
          type: "원격",
          category: "인문",
          subCategory: "언어/문학",
          title: "비밀번호를 분실했습니다. 빨리 찾고싶어요 알려주세요!",
          date: "2023.02.15",
        },
        3: {
          state: "승인 완료",
          type: "유튜브",
          category: "인문",
          subCategory: "언어/문학",
          title: "비밀번호를 분실했습니다. 빨리 찾고싶어요 알려주세요!",
          date: "2023.02.15",
        },
        4: {
          state: "접수 완료",
          type: "유튜브",
          category: "인문",
          subCategory: "언어/문학",
          title: "비밀번호를 분실했습니다. 빨리 찾고싶어요 알려주세요!",
          date: "2023.02.15",
        },
        5: {
          state: "접수 완료",
          type: "유튜브",
          category: "인문",
          subCategory: "언어/문학",
          title: "비밀번호를 분실했습니다. 빨리 찾고싶어요 알려주세요!",
          date: "2023.02.15",
        },
        6: {
          state: "접수 완료",
          type: "유튜브",
          category: "인문",
          subCategory: "언어/문학",
          title: "비밀번호를 분실했습니다. 빨리 찾고싶어요 알려주세요!",
          date: "2023.02.15",
        },
        7: {
          state: "접수 완료",
          type: "유튜브",
          category: "인문",
          subCategory: "언어/문학",
          title: "비밀번호를 분실했습니다. 빨리 찾고싶어요 알려주세요!",
          date: "2023.02.15",
        },
        8: {
          state: "접수 완료",
          type: "유튜브",
          category: "인문",
          subCategory: "언어/문학",
          title: "비밀번호를 분실했습니다. 빨리 찾고싶어요 알려주세요!",
          date: "2023.02.15",
        },
      },
      keys: [0, 1, 2, 3, 4, 5, 6, 7, 8],
    };
  },
});
